apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: java-app-deploy
  name: java-app-deploy
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: java-app-deploy
  type: NodePort
status:
  loadBalancer: {}
